WorkHands/RAPiDSkills

- Procfile
Issue #39
* Adds a Procfile so Puma is used for the web server
* Configured CodeShip to run tests
* Set up the requirement that Codeship tests pass before PRs can be merged
* Added automatic deploys from the master branch to Heroku production app
@Pcushing I don't have permissions to add new Heroku apps, so I can't set up a staging app yet.  For the `rapid-skills` production app, I added the free Heroku Postgres version for now, but let me know if you want me to provision something bigger from the get-go.
> Staging and production app setup

- app/admin/users.rb
- app/views/admin/users/change_password.html.erb
closes #57
- Remove password fields from user form
- Add Change Password button to change password
> Add separate change password page for users on admin dashboard

- app/models/data_import.rb
- db/seeds.rb
- spec/requests/admin/data_imports_spec.rb
> Create organization if it does not exist on data import

- app/services/api/v1/import_occupation_standard.rb
- config/routes.rb
#125 
- Fix issue where duplicate occupation standards were getting created when doing file import
- Display the nicer Active Admin login page
> Fix multiple record creation of occupation standards on file import

- Gemfile
- Gemfile.lock
- app/controllers/api/v1/occupation_standards_controller.rb
- app/lib/docs/public/api/v1/docs/index.html
- app/services/api/v1/pagination_link_generator.rb
- config/initializers/kaminari_config.rb
- spec/requests/api/v1/occupation_standards_spec.rb
> Add pagination for standards

- Dockerfile.prod
- README.md
- config/boot.rb
- docker-compose.yml
- vue/.env
- vue/.env.development
> Build vue files during deploy

- app/controllers/api/v1/sessions_controller.rb
- spec/requests/api/v1/sessions_spec.rb
> Include user in session response 

- app/controllers/api/v1/users/base_controller.rb
- app/controllers/api/v1/users/favorites_controller.rb
- app/controllers/api/v1/users/occupation_standards_controller.rb
- app/controllers/api/v1/users/relationships/base_controller.rb
- app/controllers/api/v1/users/relationships/favorites_controller.rb
- app/controllers/api/v1/users/relationships/occupation_standards_controller.rb
- app/lib/docs/public/api/v1/docs/index.html
- app/models/occupation_standard.rb
- app/models/user.rb
- app/policies/api/v1/user_policy.rb
- config/routes.rb
- spec/models/occupation_standard_spec.rb
- spec/requests/api/v1/users/favorites_spec.rb
- spec/requests/api/v1/users/occupation_standards_spec.rb
- spec/requests/api/v1/users/relationships/occupation_standards_spec.rb
> Endpoints for retrieving own occupation standards

- app/controllers/api/v1/leads_controller.rb
- app/controllers/api/v1/users_controller.rb
- app/lib/docs/public/api/v1/docs/index.html
- app/serializers/api/v1/user_serializer.rb
- config/routes.rb
- spec/factories/users.rb
- spec/requests/api/v1/leads_spec.rb
- spec/requests/api/v1/sessions/user_spec.rb
- spec/requests/api/v1/users_spec.rb
- vue/src/views/Follow.vue
> User registration endpoint

- app/controllers/api/v1/occupation_standards_controller.rb
- app/lib/docs/public/api/v1/docs/index.html
- app/models/occupation_standard.rb
- app/policies/api/v1/occupation_standard_policy.rb
- config/routes.rb
- spec/requests/api/v1/occupation_standards_spec.rb
> Delete occupation standard endpoint

- app/controllers/api/v1/occupation_standards_controller.rb
- app/lib/docs/public/api/v1/docs/index.html
- app/models/occupation_standard.rb
- spec/models/occupation_standard_spec.rb
- spec/requests/api/v1/occupation_standards_spec.rb
- Allows passing of title parameter when cloning standard
- Outputs error messages from failed clone
> Output errors from clone method

- app/controllers/api/v1/occupation_standards_controller.rb
- app/lib/docs/public/api/v1/docs/index.html
- app/models/occupation_standard.rb
- app/serializers/api/v1/occupation_standard_serializer.rb
- config/routes.rb
- spec/requests/api/v1/occupation_standards_spec.rb
> Return creator object with occupation standard response

- app/controllers/api/v1/occupation_standard_skills_controller.rb
- app/lib/docs/public/api/v1/docs/index.html
- app/policies/api/v1/occupation_standard_policy.rb
- config/routes.rb
- spec/requests/api/v1/occupation_standard_skills_spec.rb
> User can add new skill to occupation standard

- app/models/occupation.rb
- bin/database_import.sh
- db/migrate/20200214200522_add_index_on_title_rapids_onet_for_occupations.rb
- db/schema.rb
#179 
* adds prod data import script
* add unique index to title, rapids_code, onet_code
> Back end cleanup

- app/controllers/api/v1/occupation_standards/relationships_controller.rb
- app/controllers/api/v1/occupation_standards_controller.rb
- app/lib/docs/public/api/v1/docs/index.html
- app/models/occupation_standard.rb
- app/serializers/api/v1/occupation_standard/relationships/parent_occupation_standard_serializer.rb
- app/serializers/api/v1/occupation_standard_parent_serializer.rb
- app/serializers/api/v1/occupation_standard_serializer.rb
- config/routes.rb
- spec/requests/api/v1/occupation_standards/relationships_spec.rb
- spec/requests/api/v1/occupation_standards_spec.rb
> Serialize parent standard

- app.json
- heroku.yml
> Add release phase to migrate database for prod deploy

- app/controllers/api/v1/occupation_standard_skills_controller.rb
- app/controllers/api/v1/occupation_standard_work_processes_controller.rb
- app/lib/docs/public/api/v1/docs/index.html
- app/serializers/api/v1/occupation_standard_skill_serializer.rb
- app/serializers/api/v1/occupation_standard_work_process_serializer.rb
- spec/requests/api/v1/occupation_standard_skills_spec.rb
- spec/requests/api/v1/occupation_standard_work_processes_spec.rb
> Allow updating of skill and work process sort order

- app/admin/occupation_standard_skills.rb
- app/admin/occupation_standard_work_processes.rb
- app/admin/occupation_standards.rb
- app/controllers/api/v1/occupation_standard_skills_controller.rb
- app/controllers/api/v1/occupation_standard_work_processes_controller.rb
- app/controllers/api/v1/occupation_standards/relationships/skills_controller.rb
- app/controllers/api/v1/occupation_standards/relationships/work_processes_controller.rb
- app/controllers/api/v1/occupation_standards_controller.rb
- app/models/occupation_standard.rb
- app/models/occupation_standard_skill.rb
- app/models/occupation_standard_work_process.rb
- docker-compose.yml
- spec/models/occupation_standard_spec.rb
- spec/requests/api/v1/occupation_standard_skills_spec.rb
- spec/requests/api/v1/occupation_standard_work_processes_spec.rb
- spec/requests/api/v1/occupation_standards/relationships/skills_spec.rb
- spec/requests/api/v1/occupation_standards/relationships/work_processes_spec.rb
- spec/requests/api/v1/occupation_standards_spec.rb
> Regenerate download docs after standard is updated

- app/services/api/v1/import_occupation_standard.rb
- spec/requests/admin/data_imports_spec.rb
> Generate excel/pdf docs after data import

- vue/src/components/AppInnerLanding.vue
- vue/src/models/OccupationStandard.ts
- vue/src/models/Session.ts
- vue/src/models/User.ts
- vue/src/store/session/actions.ts
- vue/src/views/Home.vue
- vue/src/views/SignUp.vue
@Pcushing this fixes the bug where logged out people can't view standards
> #240 - sign up

- vue/src/views/SignUp.vue
@Pcushing params are `name`, `organizationName`, and `email`
> #228 - using query params for user initialization on sign up page

- .gitignore
- README.md
- config/docker.env
- vue/package.json
- vue/src/components/StandardSkill.vue
- vue/src/components/StandardWorkProcess.vue
- vue/src/main.ts
- vue/src/models/OccupationStandard.ts
- vue/src/store/session/actions.ts
- vue/src/store/standards/actions.ts
- vue/src/store/user/actions.ts
- vue/src/views/Standard.vue
- vue/vue.config.js
- vue/yarn.lock
@littleforest I asked a question in https://github.com/WorkHands/RAPiDSkills/issues/241 about `RAPID_SKILLS_ENVIRONMENT` that we should resolve before merging this.
> #241 - rollbar

- config/environments/production.rb
> Force https protocol on production 

- vue/src/components/AppInnerDashboard.vue
- vue/src/components/SearchOccupations.vue
- vue/src/components/Standard.vue
- vue/src/components/StandardNavBarActions.vue
- vue/src/models/ModelBase.ts
- vue/src/models/OccupationStandard.ts
- vue/src/router/index.ts
- vue/src/scss/colors.scss
- vue/src/scss/standards.scss
- vue/src/store/user/actions.ts
- vue/src/store/user/index.ts
- vue/src/store/user/mutations.ts
- vue/src/utilities/font-awesome.ts
- vue/src/views/Dashboard.vue
- vue/src/views/Duplicate.vue
- vue/src/views/Favorites.vue
Save button is not perfect yet but it is functional
> Standard Save button, Favorites, Browser autocomplete bug

- app/lib/notify.rb
- app/models/data_import.rb
- app/models/occupation.rb
- app/services/api/v1/import_occupation_standard.rb
- db/migrate/20200225185645_remove_rapids_code_unique_index_from_occupations.rb
- db/schema.rb
- lib/tasks/occupations.rake
- spec/factories/occupations.rb
- spec/fixtures/files/dog_walking.csv
- spec/models/occupation_spec.rb
- spec/requests/admin/data_imports_spec.rb
- spec/services/api/v1/import_occupation_standard_spec.rb
> Data import fixes

- app/controllers/api/v1/users_controller.rb
- spec/requests/api/v1/users_spec.rb
> Sign up bug fix

- app/controllers/api/v1/leads_controller.rb
- app/controllers/api/v1/users_controller.rb
- spec/requests/api/v1/leads_spec.rb
closes #301
@Pcushing Devise actually already handles the automatic downcasing of email upon save, but I made some changes to use Devise methods to retrieve from the db so it will also take case of case issues.
> Use Devise methods to retrieve user to handle email case sensitivity

- app/controllers/api/v1/users_controller.rb
- app/lib/docs/public/api/v1/docs/index.html
- app/models/user.rb
- app/policies/api/v1/user_policy.rb
- app/serializers/api/v1/user_serializer.rb
- config/routes.rb
- db/migrate/20200323210613_add_settings_to_users.rb
- db/schema.rb
- spec/requests/api/v1/users_spec.rb
> Add get, update user methods; add settings field

- README.md
- app/controllers/api/v1/occupation_standard_skills_controller.rb
- app/controllers/api/v1/occupation_standards/occupation_standard_skills_controller.rb
- app/controllers/api/v1/occupations_controller.rb
- app/lib/docs/public/api/v1/docs/index.html
- app/models/occupation.rb
- app/models/occupation_standard_skill.rb
- app/models/skill.rb
- app/serializers/api/v1/occupation_standard_skill_search_serializer.rb
- config/routes.rb
- spec/factories/occupation_standards.rb
- spec/models/occupation_standard_skill_spec.rb
- spec/models/skill_spec.rb
- spec/requests/api/v1/categories/occupation_standard_skills_spec.rb
- spec/requests/api/v1/occupation_standard_skills_spec.rb
- spec/requests/api/v1/occupation_standards/occupation_standard_skills_spec.rb
- spec/support/searchkick.rb
> Skills search

- README.md
- app/admin/occupation_standards.rb
- app/admin/organizations.rb
- app/controllers/api/v1/occupation_standard_skills_controller.rb
- app/models/occupation_standard_skill.rb
- db/migrate/20200331195516_add_index_on_description_to_skills.rb
- db/schema.rb
- spec/models/occupation_standard_skill_spec.rb
- spec/requests/api/v1/occupation_standard_skills_spec.rb
Fixes Rollbar items 20, 30
* Fix issue when client tries to create a skill that already exists on the standard
* Do not display type for Organization resource in Active Admin since not in use currently
> Rollbar error fixes

- vue/src/components/Standard.vue
- vue/src/components/StandardWorkProcess.vue
- vue/src/scss/dashboard.scss
- vue/src/views/Dashboard.vue
- vue/src/views/Standard.vue
Testing out some quick copy changes to ensure they deploy before making some other changes tomorrow.
> Testing copy changes
